# Generated by Django 5.0.6 on 2024-07-13 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masteradmin.userrole'),
        ),
    ]
