# Generated by Django 5.0.6 on 2024-07-15 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0002_alter_customer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertransactions',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='masteradmin.savingaccount'),
        ),
        migrations.AlterField(
            model_name='transfertransactions',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='masteradmin.savingaccount'),
        ),
    ]
