# Generated by Django 2.1.4 on 2019-01-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0002_auto_20190119_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingaccount',
            name='is_active',
            field=models.IntegerField(null=True),
        ),
    ]
