# Generated by Django 5.0.7 on 2024-08-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0002_personal_loan_emi'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emi',
            name='interest_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='emi',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
