# Generated by Django 2.1.4 on 2019-01-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0003_savingaccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingaccount',
            name='member',
            field=models.CharField(max_length=20),
        ),
    ]
