# Generated by Django 5.0.7 on 2024-09-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0003_loanemischedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='LOANEMIPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteradmin.personal_loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masteradmin.customer')),
            ],
        ),
    ]
