# Generated by Django 5.0.7 on 2024-09-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0004_loanemipayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LOANEMISchedule',
        ),
    ]
