# Generated by Django 2.1.4 on 2019-01-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0004_auto_20190120_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fd',
            name='associated_member',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rd',
            name='associated_member',
            field=models.CharField(max_length=20),
        ),
    ]
