# Generated by Django 5.0.7 on 2024-09-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0005_delete_loanemischedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdeposit',
            name='is_active',
            field=models.IntegerField(null=True),
        ),
    ]
