# Generated by Django 2.1.4 on 2019-01-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0006_auto_20190121_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='agent',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='landline',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='landmark',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locality',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
