# Generated by Django 5.0.7 on 2024-09-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0007_loanemipayment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanemipayment',
            name='is_active',
        ),
    ]
