# Generated by Django 2.1.4 on 2019-01-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0008_auto_20190122_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
