# Generated by Django 5.0.7 on 2024-09-23 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0009_personal_loan_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_loan',
            name='is_active',
        ),
    ]
