# Generated by Django 2.1.4 on 2019-01-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0009_auto_20190122_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='FD_scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=200)),
                ('interest_rate', models.CharField(max_length=100)),
                ('tenure', models.CharField(max_length=50)),
                ('breakable', models.IntegerField()),
                ('is_applicable', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RD_scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=200)),
                ('interest_rate', models.CharField(max_length=100)),
                ('tenure', models.CharField(max_length=50)),
                ('breakable', models.IntegerField()),
                ('is_applicable', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
