# Generated by Django 2.1.4 on 2019-01-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0010_fd_scheme_rd_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd',
            name='scheme',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rd',
            name='scheme',
            field=models.IntegerField(null=True),
        ),
    ]
