# Generated by Django 5.0.7 on 2024-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0010_remove_personal_loan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_loan',
            name='is_active',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
