# Generated by Django 5.0.7 on 2024-09-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0011_personal_loan_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_loan',
            name='is_active',
            field=models.IntegerField(null=True),
        ),
    ]
