# Generated by Django 5.0.7 on 2024-09-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0012_alter_personal_loan_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='agent',
        ),
    ]
