# Generated by Django 2.1.4 on 2019-01-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0013_auto_20190128_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='member',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='debittransaction',
            name='member',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
