# Generated by Django 2.1.4 on 2019-01-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0015_auto_20190129_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='associated_member',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
