# Generated by Django 2.1.4 on 2019-01-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0016_auto_20190201_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='member',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='debittransaction',
            name='member',
            field=models.CharField(max_length=20),
        ),
    ]
