# Generated by Django 2.1.4 on 2019-01-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0017_auto_20190201_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='debittransaction',
            name='beneficiary',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
