# Generated by Django 2.1.4 on 2019-02-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masteradmin', '0019_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
